const CATS = {
  "Cultura":         { c:"#17A2A2" },
  "Ciencia":         { c:"#1E7A5F" },
  "Historia":        { c:"#DD9414" },
  "Entretenimiento": { c:"#D6336C" },
  "Deportes":        { c:"#D9531E" },
  "Sorpresa":        { c:"#8B6BD8", x2:true }
};

const QS = [
{c:"Cultura",q:"¿En qué ciudad está el Coliseo?",o:["Atenas","Roma","Estambul","Nápoles"],a:1},
{c:"Cultura",q:"¿En qué país está el Taj Mahal?",o:["China","India","Turquía","Irán"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Australia?",o:["Sídney","Melbourne","Canberra","Perth"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de Canadá?",o:["Toronto","Vancouver","Ottawa","Montreal"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de Marruecos?",o:["Casablanca","Rabat","Marrakech","Fez"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Brasil?",o:["Río de Janeiro","São Paulo","Brasilia","Salvador"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de Turquía?",o:["Estambul","Ankara","Esmirna","Bursa"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Suiza?",o:["Zúrich","Ginebra","Berna","Basilea"],a:2},
{c:"Cultura",q:"¿En qué país está el monte Everest (en su frontera sur)?",o:["India","China","Nepal","Bután"],a:2},
{c:"Cultura",q:"¿Qué país regaló la Estatua de la Libertad a Estados Unidos?",o:["Reino Unido","España","Francia","Italia"],a:2},
{c:"Cultura",q:"¿En qué país nació el tango?",o:["Uruguay","Argentina","Chile","Paraguay"],a:1},
{c:"Cultura",q:"¿Qué civilización construyó Chichén Itzá?",o:["Inca","Azteca","Maya","Tolteca"],a:2},
{c:"Cultura",q:"¿En qué país está Machu Picchu?",o:["Bolivia","Ecuador","Perú","Colombia"],a:2},
{c:"Cultura",q:"¿Cuál es el idioma oficial de Brasil?",o:["Español","Portugués","Brasileño","Guaraní"],a:1},
{c:"Cultura",q:"¿Qué idioma tiene más hablantes nativos en el mundo?",o:["Inglés","Chino mandarín","Español","Hindi"],a:1},
{c:"Cultura",q:"¿Cuál es la moneda de Japón?",o:["Yuan","Won","Yen","Ringgit"],a:2},
{c:"Cultura",q:"¿Cuál es la moneda del Reino Unido?",o:["Euro","Libra esterlina","Corona","Franco"],a:1},
{c:"Cultura",q:"¿Cuál es el río más largo de América del Sur?",o:["Orinoco","Paraná","Amazonas","Magdalena"],a:2},
{c:"Cultura",q:"¿Cuál es el desierto más grande del mundo?",o:["Sahara","Gobi","Atacama","Antártico"],a:3},
{c:"Cultura",q:"¿Qué país tiene forma de bota?",o:["España","Italia","Grecia","Portugal"],a:1},
{c:"Cultura",q:"¿En qué continente está Egipto?",o:["Asia","Europa","África","Oceanía"],a:2},
{c:"Cultura",q:"¿Cuál es el país más grande del mundo por territorio?",o:["Canadá","China","Rusia","Estados Unidos"],a:2},
{c:"Cultura",q:"¿Cuál es el océano más grande?",o:["Atlántico","Índico","Ártico","Pacífico"],a:3},
{c:"Cultura",q:"¿En qué país se encuentra la Torre Eiffel?",o:["Italia","Francia","Bélgica","Suiza"],a:1},
{c:"Cultura",q:"¿Qué muralla es visible como la construcción más larga del mundo?",o:["Muralla de Adriano","Gran Muralla China","Muralla de Ávila","Muro de Berlín"],a:1},
{c:"Cultura",q:"¿En qué país está la ciudad de Petra?",o:["Egipto","Jordania","Siria","Líbano"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Egipto?",o:["Alejandría","Luxor","El Cairo","Asuán"],a:2},
{c:"Cultura",q:"¿Qué país tiene más habitantes en América Latina?",o:["México","Brasil","Argentina","Colombia"],a:1},
{c:"Cultura",q:"¿En qué país está la Sagrada Familia?",o:["Portugal","Italia","España","Francia"],a:2},
{c:"Cultura",q:"¿Cuál es el país más pequeño de América del Sur?",o:["Uruguay","Surinam","Guyana","Ecuador"],a:1},
{c:"Cultura",q:"¿En qué ciudad está la Casa Blanca?",o:["Nueva York","Washington D. C.","Boston","Chicago"],a:1},
{c:"Cultura",q:"¿Qué mar separa Europa de África?",o:["Mar Negro","Mar Rojo","Mar Mediterráneo","Mar Caspio"],a:2},
{c:"Cultura",q:"¿Cuál es el lago más grande del mundo por superficie?",o:["Lago Victoria","Mar Caspio","Lago Superior","Lago Baikal"],a:1},
{c:"Cultura",q:"¿En qué país está la ciudad de Marrakech?",o:["Argelia","Túnez","Marruecos","Egipto"],a:2},
{c:"Cultura",q:"¿Qué país africano tiene más población?",o:["Egipto","Etiopía","Nigeria","Sudáfrica"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de Argentina?",o:["Córdoba","Rosario","Buenos Aires","Mendoza"],a:2},
{c:"Cultura",q:"¿En qué país está el Cristo Redentor?",o:["Argentina","Brasil","Portugal","México"],a:1},
{c:"Cultura",q:"¿Qué país tiene el mayor número de volcanes activos?",o:["Japón","Chile","Indonesia","Italia"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de Corea del Sur?",o:["Busan","Seúl","Incheon","Daegu"],a:1},
{c:"Cultura",q:"¿En qué país se originó la pizza?",o:["Grecia","Italia","Francia","España"],a:1},
{c:"Cultura",q:"¿Cuál es el país más poblado del mundo?",o:["China","Estados Unidos","India","Indonesia"],a:2},
{c:"Cultura",q:"¿Qué cordillera recorre el oeste de América del Sur?",o:["Los Alpes","Los Andes","Las Rocosas","El Himalaya"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Portugal?",o:["Oporto","Braga","Lisboa","Coímbra"],a:2},
{c:"Cultura",q:"¿En qué país está la ciudad de Kioto?",o:["China","Corea","Japón","Vietnam"],a:2},
{c:"Cultura",q:"¿Qué país tiene la bandera de la hoja de arce?",o:["Noruega","Canadá","Suecia","Finlandia"],a:1},
{c:"Cultura",q:"¿Cuál es el idioma oficial de Egipto?",o:["Persa","Árabe","Turco","Hebreo"],a:1},
{c:"Cultura",q:"¿En qué país está el desierto de Atacama?",o:["Perú","Bolivia","Chile","Argentina"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de la India?",o:["Bombay","Nueva Delhi","Calcuta","Bangalore"],a:1},
{c:"Cultura",q:"¿Qué país es famoso por los molinos de viento y los tulipanes?",o:["Bélgica","Dinamarca","Países Bajos","Austria"],a:2},
{c:"Cultura",q:"¿En qué país está la isla de Bali?",o:["Malasia","Indonesia","Filipinas","Tailandia"],a:1},

{c:"Ciencia",q:"¿Qué planeta es conocido como el planeta rojo?",o:["Venus","Marte","Júpiter","Saturno"],a:1},
{c:"Ciencia",q:"¿Cuál es el planeta más grande del sistema solar?",o:["Saturno","Júpiter","Neptuno","Urano"],a:1},
{c:"Ciencia",q:"¿Qué planeta tiene los anillos más visibles?",o:["Marte","Venus","Saturno","Mercurio"],a:2},
{c:"Ciencia",q:"¿Cuál es el elemento químico con símbolo O?",o:["Oro","Osmio","Oxígeno","Plata"],a:2},
{c:"Ciencia",q:"¿Cuál es el símbolo químico del oro?",o:["Or","Au","Ag","Go"],a:1},
{c:"Ciencia",q:"¿Cuántos huesos tiene aproximadamente un adulto?",o:["186","206","226","256"],a:1},
{c:"Ciencia",q:"¿Qué órgano bombea la sangre en el cuerpo?",o:["Pulmón","Hígado","Corazón","Riñón"],a:2},
{c:"Ciencia",q:"¿Cuál es el hueso más largo del cuerpo humano?",o:["Húmero","Fémur","Tibia","Peroné"],a:1},
{c:"Ciencia",q:"¿Qué gas absorben las plantas para hacer fotosíntesis?",o:["Oxígeno","Nitrógeno","Dióxido de carbono","Hidrógeno"],a:2},
{c:"Ciencia",q:"¿Qué vitamina produce el cuerpo con la luz solar?",o:["A","B12","C","D"],a:3},
{c:"Ciencia",q:"¿Cuántos corazones tiene un pulpo?",o:["1","2","3","4"],a:2},
{c:"Ciencia",q:"¿Cuántas patas tiene una araña?",o:["6","8","10","12"],a:1},
{c:"Ciencia",q:"¿Cuál es el animal terrestre más rápido?",o:["León","Guepardo","Antílope","Caballo"],a:1},
{c:"Ciencia",q:"¿Cuál es el mamífero más grande del mundo?",o:["Elefante africano","Ballena azul","Orca","Jirafa"],a:1},
{c:"Ciencia",q:"¿Cuál es el ave más grande del mundo?",o:["Cóndor","Avestruz","Emú","Pelícano"],a:1},
{c:"Ciencia",q:"¿Qué animal es el símbolo de la longevidad por vivir más de 100 años?",o:["Tortuga","Conejo","Zorro","Ardilla"],a:0},
{c:"Ciencia",q:"¿Cuál es el metal líquido a temperatura ambiente?",o:["Plomo","Mercurio","Estaño","Litio"],a:1},
{c:"Ciencia",q:"¿A qué velocidad viaja la luz aproximadamente?",o:["300 mil km/s","150 mil km/s","500 mil km/s","1 millón km/s"],a:0},
{c:"Ciencia",q:"¿Qué ciencia estudia los terremotos?",o:["Meteorología","Sismología","Geología marina","Astronomía"],a:1},
{c:"Ciencia",q:"¿Qué estudia la botánica?",o:["Animales","Plantas","Rocas","Estrellas"],a:1},
{c:"Ciencia",q:"¿Cómo se llama la capa de gases que rodea la Tierra?",o:["Litosfera","Atmósfera","Hidrosfera","Biosfera"],a:1},
{c:"Ciencia",q:"¿Qué porcentaje de la Tierra está cubierto de agua, aproximadamente?",o:["50%","60%","70%","85%"],a:2},
{c:"Ciencia",q:"¿Cuál es el punto más profundo del océano?",o:["Fosa de las Marianas","Fosa de Java","Fosa de Perú","Mar Muerto"],a:0},
{c:"Ciencia",q:"¿Qué produce el choque de placas tectónicas?",o:["Mareas","Terremotos","Auroras","Eclipses"],a:1},
{c:"Ciencia",q:"¿Cuál es el árbol más alto del mundo?",o:["Baobab","Secuoya","Eucalipto","Ceiba"],a:1},
{c:"Ciencia",q:"¿Cuántos planetas tiene el sistema solar?",o:["7","8","9","10"],a:1},
{c:"Ciencia",q:"¿Qué astro ilumina la Luna?",o:["La Tierra","El Sol","Marte","Venus"],a:1},
{c:"Ciencia",q:"¿Cuánto tarda la Tierra en dar una vuelta al Sol?",o:["30 días","365 días","24 horas","100 días"],a:1},
{c:"Ciencia",q:"¿Cuál es el planeta más cercano al Sol?",o:["Venus","Mercurio","Marte","Tierra"],a:1},
{c:"Ciencia",q:"¿Qué fuerza nos mantiene pegados al suelo?",o:["Magnetismo","Gravedad","Fricción","Presión"],a:1},
{c:"Ciencia",q:"¿Cuál es la fórmula química del agua?",o:["CO2","H2O","O2","NaCl"],a:1},
{c:"Ciencia",q:"¿A qué temperatura hierve el agua a nivel del mar?",o:["50 °C","80 °C","100 °C","150 °C"],a:2},
{c:"Ciencia",q:"¿A qué temperatura se congela el agua?",o:["0 °C","-10 °C","5 °C","10 °C"],a:0},
{c:"Ciencia",q:"¿Qué órgano del cuerpo humano es el más grande?",o:["Hígado","Piel","Pulmón","Intestino"],a:1},
{c:"Ciencia",q:"¿Cuántos dientes tiene un adulto normalmente?",o:["28","30","32","36"],a:2},
{c:"Ciencia",q:"¿Qué grupo sanguíneo es donante universal?",o:["A+","AB+","O-","B-"],a:2},
{c:"Ciencia",q:"¿Qué animal produce la miel?",o:["Avispa","Abeja","Hormiga","Mosca"],a:1},
{c:"Ciencia",q:"¿Cuál es el insecto más numeroso del planeta?",o:["Mosca","Hormiga","Escarabajo","Mosquito"],a:2},
{c:"Ciencia",q:"¿Qué animal cambia de color para camuflarse?",o:["Camaleón","Cocodrilo","Tortuga","Iguana"],a:0},
{c:"Ciencia",q:"¿Qué parte de la planta absorbe el agua?",o:["Hojas","Tallo","Raíz","Flor"],a:2},
{c:"Ciencia",q:"¿Qué gas necesitamos para respirar?",o:["Nitrógeno","Oxígeno","Helio","Metano"],a:1},
{c:"Ciencia",q:"¿Qué instrumento mide la temperatura?",o:["Barómetro","Termómetro","Higrómetro","Altímetro"],a:1},
{c:"Ciencia",q:"¿Qué científico formuló la teoría de la relatividad?",o:["Newton","Einstein","Galileo","Tesla"],a:1},
{c:"Ciencia",q:"¿Quién descubrió la penicilina?",o:["Pasteur","Fleming","Curie","Koch"],a:1},
{c:"Ciencia",q:"¿Qué científica ganó dos premios Nobel en ciencias distintas?",o:["Ada Lovelace","Marie Curie","Rosalind Franklin","Jane Goodall"],a:1},
{c:"Ciencia",q:"¿Qué molécula guarda la información genética?",o:["ARN","ADN","ATP","Proteína"],a:1},
{c:"Ciencia",q:"¿Cuántos cromosomas tiene una célula humana normal?",o:["23","46","48","64"],a:1},
{c:"Ciencia",q:"¿Qué energía produce el Sol principalmente?",o:["Química","Nuclear","Eólica","Hidráulica"],a:1},
{c:"Ciencia",q:"¿Qué fenómeno ocurre cuando la Luna tapa al Sol?",o:["Eclipse lunar","Eclipse solar","Aurora","Solsticio"],a:1},
{c:"Ciencia",q:"¿Qué animal marino es conocido por su inteligencia y sus ocho brazos?",o:["Delfín","Pulpo","Tiburón","Medusa"],a:1},

{c:"Historia",q:"¿En qué año llegó Cristóbal Colón a América?",o:["1492","1519","1453","1500"],a:0},
{c:"Historia",q:"¿Qué imperio tuvo como capital a Tenochtitlán?",o:["Maya","Inca","Azteca","Olmeca"],a:2},
{c:"Historia",q:"¿Qué imperio construyó Machu Picchu?",o:["Azteca","Maya","Inca","Olmeca"],a:2},
{c:"Historia",q:"¿Qué ciudad quedó sepultada por el Vesubio?",o:["Roma","Pompeya","Atenas","Cartago"],a:1},
{c:"Historia",q:"¿Quién fue el libertador de gran parte de Sudamérica?",o:["San Martín","Simón Bolívar","Sucre","O'Higgins"],a:1},
{c:"Historia",q:"¿En qué país comenzó la Revolución Industrial?",o:["Francia","Alemania","Reino Unido","Estados Unidos"],a:2},
{c:"Historia",q:"¿Qué faraón es famoso por su tumba hallada intacta en 1922?",o:["Ramsés II","Tutankamón","Keops","Akenatón"],a:1},
{c:"Historia",q:"¿Qué muro cayó en 1989?",o:["Muro de Adriano","Muro de Berlín","Gran Muralla","Muro de los Lamentos"],a:1},
{c:"Historia",q:"¿En qué año terminó la Segunda Guerra Mundial?",o:["1943","1945","1947","1950"],a:1},
{c:"Historia",q:"¿Quién fue el primer ser humano en pisar la Luna?",o:["Buzz Aldrin","Yuri Gagarin","Neil Armstrong","Michael Collins"],a:2},
{c:"Historia",q:"¿En qué década llegó el ser humano a la Luna?",o:["1950","1960","1970","1980"],a:1},
{c:"Historia",q:"¿Quién pintó la Mona Lisa?",o:["Miguel Ángel","Rafael","Leonardo da Vinci","Botticelli"],a:2},
{c:"Historia",q:"¿Quién pintó el techo de la Capilla Sixtina?",o:["Miguel Ángel","Da Vinci","Caravaggio","Donatello"],a:0},
{c:"Historia",q:"¿Quién escribió Don Quijote de la Mancha?",o:["Lope de Vega","Miguel de Cervantes","Quevedo","Góngora"],a:1},
{c:"Historia",q:"¿Qué reina de Egipto fue aliada de Marco Antonio?",o:["Nefertiti","Cleopatra","Hatshepsut","Isis"],a:1},
{c:"Historia",q:"¿En qué año cayó el Imperio Romano de Occidente?",o:["476","1453","800","1066"],a:0},
{c:"Historia",q:"¿Quién lideró la independencia de la India con la no violencia?",o:["Nehru","Gandhi","Bose","Patel"],a:1},
{c:"Historia",q:"¿Qué expedición dio la primera vuelta al mundo?",o:["La de Colón","La de Magallanes y Elcano","La de Vespucio","La de Cook"],a:1},
{c:"Historia",q:"¿En qué siglo ocurrió la Revolución Francesa?",o:["XVI","XVII","XVIII","XIX"],a:2},
{c:"Historia",q:"¿Qué civilización construyó el Coliseo?",o:["Griega","Romana","Egipcia","Persa"],a:1},
{c:"Historia",q:"¿De qué país se independizó Estados Unidos?",o:["Francia","España","Reino Unido","Portugal"],a:2},
{c:"Historia",q:"¿Qué barco famoso se hundió en 1912?",o:["Lusitania","Britannic","Titanic","Queen Mary"],a:2},
{c:"Historia",q:"¿Quién fue el primer presidente de Estados Unidos?",o:["Jefferson","Lincoln","Washington","Adams"],a:2},
{c:"Historia",q:"¿Qué presidente estadounidense abolió la esclavitud?",o:["Washington","Lincoln","Roosevelt","Kennedy"],a:1},
{c:"Historia",q:"¿En qué año comenzó la Primera Guerra Mundial?",o:["1912","1914","1918","1920"],a:1},
{c:"Historia",q:"¿Qué país lanzó el primer satélite artificial, el Sputnik?",o:["Estados Unidos","Unión Soviética","Alemania","China"],a:1},
{c:"Historia",q:"¿Quién fue el primer humano en viajar al espacio?",o:["Armstrong","Yuri Gagarin","Glenn","Tereshkova"],a:1},
{c:"Historia",q:"¿Qué imperio dominó gran parte del Mediterráneo antes de Roma?",o:["Persa","Griego","Otomano","Mongol"],a:1},
{c:"Historia",q:"¿Quién conquistó gran parte de Asia creando el Imperio Mongol?",o:["Atila","Gengis Kan","Tamerlán","Kublai"],a:1},
{c:"Historia",q:"¿En qué ciudad se firmó la independencia de Estados Unidos?",o:["Boston","Filadelfia","Nueva York","Washington"],a:1},
{c:"Historia",q:"¿Qué invento de Gutenberg cambió la difusión del conocimiento?",o:["El telescopio","La imprenta","El reloj","La brújula"],a:1},
{c:"Historia",q:"¿Quién escribió la teoría de la evolución por selección natural?",o:["Mendel","Darwin","Lamarck","Linneo"],a:1},
{c:"Historia",q:"¿Qué muro dividió Alemania durante la Guerra Fría?",o:["Muro de Praga","Muro de Berlín","Línea Maginot","Telón de acero"],a:1},
{c:"Historia",q:"¿Qué civilización inventó los Juegos Olímpicos antiguos?",o:["Romana","Griega","Egipcia","Persa"],a:1},
{c:"Historia",q:"¿En qué año se fundó la Organización de las Naciones Unidas?",o:["1919","1945","1950","1960"],a:1},
{c:"Historia",q:"¿Quién fue conocida como la Dama de la Lámpara en enfermería?",o:["Marie Curie","Florence Nightingale","Clara Barton","Juana de Arco"],a:1},
{c:"Historia",q:"¿Qué emperador francés fue derrotado en Waterloo?",o:["Luis XIV","Napoleón","Carlos X","Robespierre"],a:1},
{c:"Historia",q:"¿Qué civilización construyó las pirámides de Giza?",o:["Nubia","Egipcia","Fenicia","Sumeria"],a:1},
{c:"Historia",q:"¿Qué escritura usaban los antiguos egipcios?",o:["Cuneiforme","Jeroglífica","Rúnica","Alfabética"],a:1},
{c:"Historia",q:"¿Quién descubrió el Pacífico cruzando Panamá?",o:["Cortés","Núñez de Balboa","Pizarro","Ponce de León"],a:1},
{c:"Historia",q:"¿Qué conquistador español venció al Imperio Inca?",o:["Hernán Cortés","Francisco Pizarro","Valdivia","Almagro"],a:1},
{c:"Historia",q:"¿Qué conquistador español llegó al Imperio Azteca?",o:["Pizarro","Hernán Cortés","Balboa","Orellana"],a:1},
{c:"Historia",q:"¿En qué año cayó Constantinopla?",o:["1453","1492","1066","1215"],a:0},
{c:"Historia",q:"¿Qué documento inglés de 1215 limitó el poder del rey?",o:["Carta Magna","Bill of Rights","Acta de Unión","Domesday"],a:0},
{c:"Historia",q:"¿Qué guerra enfrentó al Norte y al Sur de Estados Unidos?",o:["Guerra de Independencia","Guerra Civil","Guerra de 1812","Guerra Hispano"],a:1},
{c:"Historia",q:"¿Qué antiguo pueblo creó el primer alfabeto que influyó al nuestro?",o:["Fenicios","Vikingos","Celtas","Hititas"],a:0},
{c:"Historia",q:"¿Qué famosa biblioteca antigua se ubicaba en Egipto?",o:["De Pérgamo","De Alejandría","De Nínive","De Éfeso"],a:1},
{c:"Historia",q:"¿Quién dirigió la Revolución Cubana en 1959?",o:["Che Guevara","Fidel Castro","Batista","Martí"],a:1},
{c:"Historia",q:"¿Qué líder sudafricano fue preso 27 años y luego presidente?",o:["Mandela","Tutu","Mbeki","Biko"],a:0},
{c:"Historia",q:"¿En qué año llegó el hombre a la Luna?",o:["1965","1969","1972","1975"],a:1},

{c:"Entretenimiento",q:"¿Cómo se llama el mago protagonista de la saga de J. K. Rowling?",o:["Ron Weasley","Harry Potter","Draco Malfoy","Neville"],a:1},
{c:"Entretenimiento",q:"¿Cómo se llama el reino de Elsa en Frozen?",o:["Arendelle","Corona","Dunbroch","Agrabah"],a:0},
{c:"Entretenimiento",q:"¿Qué película animada transcurre en la tierra de los muertos mexicana?",o:["Encanto","Coco","El libro de la vida","Moana"],a:1},
{c:"Entretenimiento",q:"¿De qué color es Shrek?",o:["Azul","Verde","Gris","Café"],a:1},
{c:"Entretenimiento",q:"¿Qué película tiene un pez payaso llamado Nemo?",o:["Shark Tale","Buscando a Nemo","Moana","Luca"],a:1},
{c:"Entretenimiento",q:"¿En qué país nació el anime?",o:["China","Corea","Japón","Tailandia"],a:2},
{c:"Entretenimiento",q:"¿De qué país es originario el K-pop?",o:["Japón","China","Corea del Sur","Tailandia"],a:2},
{c:"Entretenimiento",q:"¿De qué país es el grupo BTS?",o:["Japón","Corea del Sur","China","Filipinas"],a:1},
{c:"Entretenimiento",q:"¿De qué país es la banda Coldplay?",o:["Estados Unidos","Australia","Reino Unido","Irlanda"],a:2},
{c:"Entretenimiento",q:"¿De qué país eran los Beatles?",o:["Estados Unidos","Reino Unido","Irlanda","Canadá"],a:1},
{c:"Entretenimiento",q:"¿Qué artista es conocida como la reina del pop?",o:["Beyoncé","Madonna","Rihanna","Shakira"],a:1},
{c:"Entretenimiento",q:"¿Qué cantante es conocido como el rey del pop?",o:["Elvis","Michael Jackson","Prince","Freddie Mercury"],a:1},
{c:"Entretenimiento",q:"¿De qué país es la cantante Shakira?",o:["México","Colombia","Venezuela","Argentina"],a:1},
{c:"Entretenimiento",q:"¿De dónde es originario el reguetón?",o:["Colombia","Puerto Rico","Panamá","Cuba"],a:1},
{c:"Entretenimiento",q:"¿Qué instrumento tiene 88 teclas?",o:["Órgano","Piano","Acordeón","Sintetizador"],a:1},
{c:"Entretenimiento",q:"¿Cuántas cuerdas tiene una guitarra clásica?",o:["4","5","6","7"],a:2},
{c:"Entretenimiento",q:"¿Qué instrumento toca un violinista con un arco?",o:["Arpa","Violín","Flauta","Trompeta"],a:1},
{c:"Entretenimiento",q:"¿Qué serie tiene un pueblo llamado Springfield?",o:["Futurama","Los Simpson","Padre de familia","South Park"],a:1},
{c:"Entretenimiento",q:"¿En qué ciudad vive Batman?",o:["Metrópolis","Ciudad Gótica","Nueva York","Central City"],a:1},
{c:"Entretenimiento",q:"¿Qué superhéroe es conocido como el hombre araña?",o:["Batman","Spider-Man","Flash","Daredevil"],a:1},
{c:"Entretenimiento",q:"¿Qué videojuego tiene un fontanero llamado Mario?",o:["Sonic","Zelda","Super Mario","Pac-Man"],a:2},
{c:"Entretenimiento",q:"¿Qué erizo azul es la mascota de Sega?",o:["Knuckles","Sonic","Tails","Shadow"],a:1},
{c:"Entretenimiento",q:"¿Qué juego consiste en construir con bloques en un mundo abierto?",o:["Fortnite","Minecraft","Roblox","Among Us"],a:1},
{c:"Entretenimiento",q:"¿En qué plataforma se hicieron famosos los bailes cortos?",o:["Facebook","TikTok","LinkedIn","Pinterest"],a:1},
{c:"Entretenimiento",q:"¿Cómo se llamaba la red social del pajarito azul antes de ser X?",o:["Facebook","Twitter","Instagram","Snapchat"],a:1},
{c:"Entretenimiento",q:"¿Qué festival brasileño es famoso mundialmente?",o:["Oktoberfest","Carnaval de Río","Tomatina","Coachella"],a:1},
{c:"Entretenimiento",q:"¿En qué país se celebra la Tomatina?",o:["Italia","España","Portugal","México"],a:1},
{c:"Entretenimiento",q:"¿Qué fiesta alemana celebra la cerveza cada otoño?",o:["Carnaval","Oktoberfest","Nochevieja","Karneval"],a:1},
{c:"Entretenimiento",q:"¿Qué premio recibe la mejor película en Hollywood?",o:["Grammy","Óscar","Emmy","Tony"],a:1},
{c:"Entretenimiento",q:"¿Qué premio se entrega a la música en Estados Unidos?",o:["Óscar","Grammy","Emmy","Globo de Oro"],a:1},
{c:"Entretenimiento",q:"¿Qué saga tiene a Luke Skywalker como protagonista?",o:["Star Trek","Star Wars","Dune","Matrix"],a:1},
{c:"Entretenimiento",q:"¿Cómo se llama el ogro verde de la película animada de DreamWorks?",o:["Hulk","Shrek","Grinch","Mike"],a:1},
{c:"Entretenimiento",q:"¿Qué animal es Simba en El Rey León?",o:["Tigre","León","Leopardo","Guepardo"],a:1},
{c:"Entretenimiento",q:"¿Qué película trata de juguetes que cobran vida?",o:["Cars","Toy Story","Up","Bichos"],a:1},
{c:"Entretenimiento",q:"¿En qué país se ambienta la película Encanto?",o:["México","Colombia","Perú","Brasil"],a:1},
{c:"Entretenimiento",q:"¿Qué instrumento es típico del flamenco español?",o:["Violín","Guitarra","Acordeón","Bandoneón"],a:1},
{c:"Entretenimiento",q:"¿Qué instrumento es característico del tango argentino?",o:["Bandoneón","Charango","Ukelele","Banjo"],a:0},
{c:"Entretenimiento",q:"¿De qué país es originaria la salsa como género popularizado?",o:["Cuba y Puerto Rico","Brasil","Argentina","Chile"],a:0},
{c:"Entretenimiento",q:"¿Qué baile es típico de Brasil?",o:["Samba","Tango","Flamenco","Merengue"],a:0},
{c:"Entretenimiento",q:"¿De qué país es originario el merengue?",o:["Cuba","República Dominicana","Panamá","Venezuela"],a:1},
{c:"Entretenimiento",q:"¿Qué streaming es famoso por su logo rojo con la letra N?",o:["Hulu","Netflix","Disney+","Max"],a:1},
{c:"Entretenimiento",q:"¿Qué juego de mesa usa fichas para hacer palabras?",o:["Monopoly","Scrabble","Risk","Clue"],a:1},
{c:"Entretenimiento",q:"¿Qué juego de mesa trata de comprar propiedades?",o:["Monopoly","Ajedrez","Damas","Uno"],a:0},
{c:"Entretenimiento",q:"¿Cuántas piezas tiene cada jugador al empezar en ajedrez?",o:["12","16","18","20"],a:1},
{c:"Entretenimiento",q:"¿Qué personaje come puntos huyendo de fantasmas?",o:["Mario","Pac-Man","Sonic","Kirby"],a:1},
{c:"Entretenimiento",q:"¿Qué película famosa tiene la frase de un barco y un iceberg?",o:["Poseidón","Titanic","Náufrago","Tiburón"],a:1},
{c:"Entretenimiento",q:"¿Qué grupo sueco es famoso por Dancing Queen?",o:["ABBA","Roxette","Ace of Base","A-ha"],a:0},
{c:"Entretenimiento",q:"¿En qué ciudad se ambienta la serie Friends?",o:["Los Ángeles","Nueva York","Chicago","Boston"],a:1},
{c:"Entretenimiento",q:"¿Qué instrumento tiene teclas blancas y negras?",o:["Batería","Piano","Trompeta","Violín"],a:1},
{c:"Entretenimiento",q:"¿Qué famosa novela tiene a un hobbit llamado Frodo?",o:["Narnia","El Señor de los Anillos","Eragon","Dune"],a:1},

{c:"Deportes",q:"¿Cada cuántos años se juega el Mundial de fútbol?",o:["2","3","4","5"],a:2},
{c:"Deportes",q:"¿Qué selección ganó el Mundial de Qatar 2022?",o:["Francia","Brasil","Argentina","Croacia"],a:2},
{c:"Deportes",q:"¿Qué país ha ganado más mundiales de fútbol?",o:["Alemania","Argentina","Brasil","Italia"],a:2},
{c:"Deportes",q:"¿En qué año se celebró el primer Mundial de fútbol?",o:["1930","1950","1924","1934"],a:0},
{c:"Deportes",q:"¿En qué país se jugó el primer Mundial de fútbol?",o:["Brasil","Uruguay","Italia","Argentina"],a:1},
{c:"Deportes",q:"¿Cuántos jugadores tiene un equipo de fútbol en cancha?",o:["9","10","11","12"],a:2},
{c:"Deportes",q:"¿Cuánto dura un partido de fútbol reglamentario?",o:["80 min","90 min","100 min","120 min"],a:1},
{c:"Deportes",q:"¿En qué deporte existe la posición de portero?",o:["Básquetbol","Voleibol","Fútbol","Béisbol"],a:2},
{c:"Deportes",q:"¿En qué país nacieron los Juegos Olímpicos?",o:["Italia","Grecia","Egipto","Turquía"],a:1},
{c:"Deportes",q:"¿Cuántos aros tiene el símbolo olímpico?",o:["4","5","6","7"],a:1},
{c:"Deportes",q:"¿Cada cuántos años se celebran los Juegos Olímpicos de verano?",o:["2","3","4","5"],a:2},
{c:"Deportes",q:"¿En qué deporte destacó Michael Jordan?",o:["Béisbol","Básquetbol","Fútbol americano","Tenis"],a:1},
{c:"Deportes",q:"¿Cuántos puntos vale un triple en básquetbol?",o:["1","2","3","4"],a:2},
{c:"Deportes",q:"¿Cuántos jugadores tiene un equipo de básquetbol en cancha?",o:["4","5","6","7"],a:1},
{c:"Deportes",q:"¿De qué país es la NBA?",o:["Canadá","Estados Unidos","México","España"],a:1},
{c:"Deportes",q:"¿Dónde se juega el torneo de Wimbledon?",o:["París","Nueva York","Londres","Melbourne"],a:2},
{c:"Deportes",q:"¿Sobre qué superficie se juega Wimbledon?",o:["Arcilla","Césped","Cemento","Sintético"],a:1},
{c:"Deportes",q:"¿En qué ciudad se juega Roland Garros?",o:["Londres","París","Roma","Madrid"],a:1},
{c:"Deportes",q:"¿En qué deporte se usa un volante o shuttlecock?",o:["Tenis","Bádminton","Squash","Pádel"],a:1},
{c:"Deportes",q:"¿Qué país inventó el taekwondo?",o:["Japón","China","Corea","Vietnam"],a:2},
{c:"Deportes",q:"¿Qué país inventó el judo?",o:["China","Japón","Corea","Tailandia"],a:1},
{c:"Deportes",q:"¿Qué país domina el rugby con los All Blacks?",o:["Australia","Sudáfrica","Nueva Zelanda","Fiyi"],a:2},
{c:"Deportes",q:"¿En qué deporte se anota un home run?",o:["Cricket","Béisbol","Golf","Fútbol"],a:1},
{c:"Deportes",q:"¿En qué deporte destaca Simone Biles?",o:["Natación","Gimnasia","Atletismo","Tenis"],a:1},
{c:"Deportes",q:"¿En qué deporte compitió Usain Bolt?",o:["Natación","Atletismo","Ciclismo","Boxeo"],a:1},
{c:"Deportes",q:"¿Qué nadador ganó más medallas olímpicas de la historia?",o:["Ian Thorpe","Michael Phelps","Mark Spitz","Caeleb Dressel"],a:1},
{c:"Deportes",q:"¿En qué país se corre mayormente el Tour de Francia?",o:["Bélgica","Francia","España","Italia"],a:1},
{c:"Deportes",q:"¿Qué color de camiseta lleva el líder del Tour de Francia?",o:["Verde","Amarilla","Roja","Blanca"],a:1},
{c:"Deportes",q:"¿En qué deporte se usa la palabra jaque mate?",o:["Damas","Ajedrez","Póker","Dominó"],a:1},
{c:"Deportes",q:"¿Cuántas casillas tiene un tablero de ajedrez?",o:["36","49","64","81"],a:2},
{c:"Deportes",q:"¿Qué se necesita para hacer un strike en boliche?",o:["Tirar 5 pinos","Tirar 8 pinos","Tirar todos los pinos","Tirar dos veces"],a:2},
{c:"Deportes",q:"¿Cuántos jugadores tiene un equipo de voleibol en cancha?",o:["5","6","7","8"],a:1},
{c:"Deportes",q:"¿En qué deporte se usa un tatami?",o:["Boxeo","Judo","Esgrima","Golf"],a:1},
{c:"Deportes",q:"¿Cuántos rounds suele tener una pelea profesional de boxeo por título?",o:["8","10","12","15"],a:2},
{c:"Deportes",q:"¿En qué deporte se compite en la Fórmula 1?",o:["Motociclismo","Automovilismo","Ciclismo","Náutica"],a:1},
{c:"Deportes",q:"¿Qué escudería de Fórmula 1 es italiana y de color rojo?",o:["McLaren","Ferrari","Williams","Renault"],a:1},
{c:"Deportes",q:"¿En qué deporte se usan palos y hoyos?",o:["Croquet","Golf","Hockey","Polo"],a:1},
{c:"Deportes",q:"¿Cuántos hoyos tiene un campo de golf reglamentario?",o:["9","12","18","21"],a:2},
{c:"Deportes",q:"¿Qué país organizó los Juegos Olímpicos de Tokio 2020?",o:["China","Japón","Corea","Australia"],a:1},
{c:"Deportes",q:"¿En qué deporte se practica el estilo mariposa?",o:["Atletismo","Natación","Gimnasia","Remo"],a:1},
{c:"Deportes",q:"¿Cuánto mide una maratón oficial aproximadamente?",o:["21 km","42 km","50 km","30 km"],a:1},
{c:"Deportes",q:"¿Cuánto mide una media maratón?",o:["10 km","21 km","30 km","15 km"],a:1},
{c:"Deportes",q:"¿En qué deporte se enfrentan un pícher y un bateador?",o:["Cricket","Béisbol","Sóftbol y béisbol","Hockey"],a:2},
{c:"Deportes",q:"¿Qué torneo de fútbol europeo es el más importante entre clubes?",o:["Europa League","Champions League","Copa del Rey","Supercopa"],a:1},
{c:"Deportes",q:"¿De qué país es el equipo Real Madrid?",o:["Portugal","España","Italia","Argentina"],a:1},
{c:"Deportes",q:"¿En qué deporte destacó Diego Maradona?",o:["Básquetbol","Fútbol","Tenis","Boxeo"],a:1},
{c:"Deportes",q:"¿Qué deporte practica Lionel Messi?",o:["Fútbol","Tenis","Rugby","Golf"],a:0},
{c:"Deportes",q:"¿Qué país ganó la Eurocopa más veces junto con Alemania?",o:["Francia","España","Italia","Países Bajos"],a:1},
{c:"Deportes",q:"¿Cuántos sets debe ganar un hombre en un Grand Slam de tenis?",o:["2","3","4","5"],a:1},
{c:"Deportes",q:"¿En qué deporte se usa el término touchdown?",o:["Rugby","Fútbol americano","Hockey","Béisbol"],a:1},

{c:"Sorpresa",q:"¿Cuántos husos horarios tiene Rusia?",o:["7","9","11","13"],a:2},
{c:"Sorpresa",q:"¿Cuál es el país más pequeño del mundo?",o:["Mónaco","Vaticano","San Marino","Malta"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene una bandera que no es rectangular?",o:["Suiza","Nepal","Qatar","Chipre"],a:1},
{c:"Sorpresa",q:"¿En qué país es de mala educación dejar propina?",o:["Japón","México","Italia","Brasil"],a:0},
{c:"Sorpresa",q:"¿Qué país tiene más islas en el mundo?",o:["Indonesia","Filipinas","Suecia","Canadá"],a:2},
{c:"Sorpresa",q:"¿Qué país no tiene ejército desde 1948?",o:["Suiza","Costa Rica","Panamá","Uruguay"],a:1},
{c:"Sorpresa",q:"¿Cuál es el idioma con más letras en su alfabeto entre estos?",o:["Español","Ruso","Inglés","Italiano"],a:1},
{c:"Sorpresa",q:"¿Qué animal duerme de pie?",o:["Perro","Caballo","Gato","Conejo"],a:1},
{c:"Sorpresa",q:"¿Qué fruta flota en el agua por su aire interior?",o:["Manzana","Uva","Cereza","Fresa"],a:0},
{c:"Sorpresa",q:"¿Qué alimento nunca se echa a perder si se guarda bien?",o:["Leche","Miel","Pan","Queso"],a:1},
{c:"Sorpresa",q:"¿Cuántos minutos tarda la luz del Sol en llegar a la Tierra?",o:["1","8","30","60"],a:1},
{c:"Sorpresa",q:"¿Qué país cambia de nombre según el idioma: Deutschland?",o:["Dinamarca","Alemania","Países Bajos","Austria"],a:1},
{c:"Sorpresa",q:"¿Qué animal tiene la lengua más larga en proporción a su cuerpo?",o:["Jirafa","Camaleón","Oso hormiguero","Rana"],a:1},
{c:"Sorpresa",q:"¿Qué océano es el más pequeño?",o:["Índico","Ártico","Atlántico","Antártico"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene la mayor esperanza de vida entre estos?",o:["Japón","Estados Unidos","Rusia","Brasil"],a:0},
{c:"Sorpresa",q:"¿Cuántos huesos tiene un recién nacido aproximadamente?",o:["206","270","150","300"],a:1},
{c:"Sorpresa",q:"¿Qué color de la bandera olímpica está en el centro?",o:["Azul","Negro","Rojo","Verde"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene más pirámides que Egipto?",o:["México","Sudán","Perú","China"],a:1},
{c:"Sorpresa",q:"¿Cuál es el único mamífero capaz de volar?",o:["Ardilla voladora","Murciélago","Colugo","Petauro"],a:1},
{c:"Sorpresa",q:"¿Qué parte del cuerpo humano nunca deja de crecer?",o:["Nariz y orejas","Manos","Pies","Dientes"],a:0},
{c:"Sorpresa",q:"¿Cuántos corazones necesita una lombriz de tierra?",o:["1","3","5","Varios arcos aórticos"],a:3},
{c:"Sorpresa",q:"¿Qué animal puede regenerar sus extremidades?",o:["Estrella de mar","Delfín","Pingüino","Búho"],a:0},
{c:"Sorpresa",q:"¿Qué país conduce por la izquierda entre estos?",o:["Francia","Reino Unido","España","Alemania"],a:1},
{c:"Sorpresa",q:"¿En qué país se inventó el papel?",o:["Egipto","China","India","Grecia"],a:1},
{c:"Sorpresa",q:"¿Dónde se inventaron los fideos según la evidencia más antigua?",o:["Italia","China","Japón","Turquía"],a:1},
{c:"Sorpresa",q:"¿Qué bebida es la más consumida del mundo después del agua?",o:["Café","Té","Refresco","Cerveza"],a:1},
{c:"Sorpresa",q:"¿Qué país produce más café del mundo?",o:["Colombia","Brasil","Vietnam","Etiopía"],a:1},
{c:"Sorpresa",q:"¿De qué planta se obtiene el chocolate?",o:["Cacao","Café","Vainilla","Coca"],a:0},
{c:"Sorpresa",q:"¿Qué especia es la más cara del mundo por peso?",o:["Vainilla","Azafrán","Cardamomo","Canela"],a:1},
{c:"Sorpresa",q:"¿Qué animal tiene huellas dactilares parecidas a las humanas?",o:["Gorila","Koala","Chimpancé","Orangután"],a:1},
{c:"Sorpresa",q:"¿Cuál es el sonido más fuerte producido por un animal?",o:["León","Ballena azul","Elefante","Lobo"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene el himno nacional más antiguo?",o:["Francia","Países Bajos","España","Japón"],a:1},
{c:"Sorpresa",q:"¿Qué ciudad tiene más habitantes en el mundo?",o:["Nueva York","Tokio","Shanghái","Ciudad de México"],a:1},
{c:"Sorpresa",q:"¿En qué país se ubica la ciudad más austral del mundo?",o:["Chile","Argentina","Nueva Zelanda","Sudáfrica"],a:1},
{c:"Sorpresa",q:"¿Qué continente no tiene países independientes?",o:["Oceanía","Antártida","África","Asia"],a:1},
{c:"Sorpresa",q:"¿Cuántos países hay aproximadamente en el mundo según la ONU?",o:["150","193","210","250"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene el mayor número de lenguas habladas?",o:["India","Papúa Nueva Guinea","Nigeria","Indonesia"],a:1},
{c:"Sorpresa",q:"¿Qué animal es el más venenoso del mundo marino?",o:["Tiburón","Avispa de mar","Pulpo","Barracuda"],a:1},
{c:"Sorpresa",q:"¿Cuánto tiempo puede vivir una cucaracha sin cabeza?",o:["Minutos","Varios días","Un año","No sobrevive"],a:1},
{c:"Sorpresa",q:"¿Qué material es el más duro que existe en la naturaleza?",o:["Acero","Diamante","Titanio","Cuarzo"],a:1},
{c:"Sorpresa",q:"¿Qué planeta gira al revés que los demás?",o:["Marte","Venus","Júpiter","Neptuno"],a:1},
{c:"Sorpresa",q:"¿Cuánto dura un día en Venus comparado con su año?",o:["Es más corto","Es más largo","Es igual","Es la mitad"],a:1},
{c:"Sorpresa",q:"¿Qué color absorbe más calor?",o:["Blanco","Negro","Amarillo","Rojo"],a:1},
{c:"Sorpresa",q:"¿Qué país inventó el fútbol moderno con sus reglas?",o:["Brasil","Inglaterra","Italia","Uruguay"],a:1},
{c:"Sorpresa",q:"¿Qué invento se atribuye a Alexander Graham Bell?",o:["Radio","Teléfono","Bombilla","Televisión"],a:1},
{c:"Sorpresa",q:"¿Cuál es la montaña más alta medida desde su base submarina?",o:["Everest","Mauna Kea","K2","Aconcagua"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene más husos horarios contando sus territorios?",o:["Rusia","Francia","Estados Unidos","China"],a:1},
{c:"Sorpresa",q:"¿Cuántos idiomas oficiales tiene Suiza?",o:["1","2","3","4"],a:3},
{c:"Sorpresa",q:"¿Qué país usa un solo huso horario pese a ser enorme?",o:["Rusia","China","Canadá","Brasil"],a:1},
{c:"Sorpresa",q:"¿Qué animal fue el primero en orbitar la Tierra?",o:["Mono","Perra Laika","Ratón","Tortuga"],a:1},

{c:"Cultura",q:"¿Cuál es la capital de Perú?",o:["Cusco","Arequipa","Lima","Trujillo"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de Colombia?",o:["Medellín","Bogotá","Cali","Cartagena"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Chile?",o:["Valparaíso","Concepción","Santiago","Antofagasta"],a:2},
{c:"Cultura",q:"¿Cuál es la capital de Grecia?",o:["Salónica","Atenas","Patras","Esparta"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Noruega?",o:["Bergen","Oslo","Estocolmo","Trondheim"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Kenia?",o:["Mombasa","Nairobi","Kisumu","Dar es Salam"],a:1},
{c:"Cultura",q:"¿Cuál es la capital de Vietnam?",o:["Ho Chi Minh","Hanói","Hue","Da Nang"],a:1},
{c:"Cultura",q:"¿En qué país está la ciudad de Dubái?",o:["Catar","Arabia Saudita","Emiratos Árabes Unidos","Kuwait"],a:2},
{c:"Cultura",q:"¿Qué río cruza la ciudad de Londres?",o:["Sena","Támesis","Danubio","Rin"],a:1},
{c:"Cultura",q:"¿Qué río cruza París?",o:["Loira","Sena","Ródano","Garona"],a:1},
{c:"Cultura",q:"¿Cuál es el río más largo de África?",o:["Congo","Níger","Nilo","Zambeze"],a:2},
{c:"Cultura",q:"¿Qué cordillera separa Europa de Asia?",o:["Cárpatos","Urales","Alpes","Balcanes"],a:1},
{c:"Cultura",q:"¿En qué país está la Gran Barrera de Coral?",o:["Indonesia","Australia","Filipinas","Fiyi"],a:1},
{c:"Cultura",q:"¿Qué idioma se habla oficialmente en Austria?",o:["Austriaco","Alemán","Húngaro","Checo"],a:1},
{c:"Cultura",q:"¿Qué moneda se usa en la mayor parte de la Unión Europea?",o:["Dólar","Euro","Libra","Franco"],a:1},
{c:"Cultura",q:"¿Cuál es la moneda de México?",o:["Peso","Real","Sol","Quetzal"],a:0},
{c:"Cultura",q:"¿En qué país se originó el sushi?",o:["China","Corea","Japón","Vietnam"],a:2},
{c:"Cultura",q:"¿De qué país es originaria la paella?",o:["Italia","España","Portugal","México"],a:1},
{c:"Cultura",q:"¿De qué país son originarios los tacos?",o:["España","México","Guatemala","Perú"],a:1},
{c:"Cultura",q:"¿Qué país es famoso por el queso gouda?",o:["Francia","Países Bajos","Suiza","Bélgica"],a:1},
{c:"Cultura",q:"¿En qué continente está Nueva Zelanda?",o:["Asia","Oceanía","América","África"],a:1},
{c:"Cultura",q:"¿Qué país tiene el territorio más al sur del mundo?",o:["Argentina","Chile","Nueva Zelanda","Sudáfrica"],a:1},
{c:"Cultura",q:"¿Cuál es el país más largo del mundo de norte a sur?",o:["Brasil","Chile","Rusia","Noruega"],a:1},
{c:"Cultura",q:"¿Qué mar baña las costas de Croacia?",o:["Mar Negro","Mar Adriático","Mar Egeo","Mar Jónico"],a:1},
{c:"Cultura",q:"¿En qué ciudad está el barrio de Manhattan?",o:["Chicago","Boston","Nueva York","Filadelfia"],a:2},
{c:"Cultura",q:"¿Qué país tiene como símbolo el canguro?",o:["Sudáfrica","Australia","Nueva Zelanda","Argentina"],a:1},
{c:"Cultura",q:"¿Qué país asiático se conoce como la tierra del sol naciente?",o:["China","Corea","Japón","Tailandia"],a:2},
{c:"Cultura",q:"¿Cuál es la ciudad más poblada de África?",o:["El Cairo","Lagos","Johannesburgo","Nairobi"],a:1},
{c:"Cultura",q:"¿En qué país está la ciudad de Praga?",o:["Polonia","Hungría","República Checa","Eslovaquia"],a:2},
{c:"Cultura",q:"¿Qué canal une el Atlántico con el Pacífico?",o:["Canal de Suez","Canal de Panamá","Canal de la Mancha","Canal de Corinto"],a:1},
{c:"Cultura",q:"¿Qué canal une el Mediterráneo con el Mar Rojo?",o:["Canal de Panamá","Canal de Suez","Canal de Kiel","Canal de Corinto"],a:1},
{c:"Cultura",q:"¿En qué país se encuentra la ciudad de Marruecos llamada Fez?",o:["Argelia","Marruecos","Túnez","Libia"],a:1},
{c:"Cultura",q:"¿Cuál es el idioma más hablado en Sudamérica?",o:["Portugués","Español","Inglés","Quechua"],a:1},
{c:"Cultura",q:"¿En qué país está la ciudad de Ushuaia, una de las más australes?",o:["Chile","Argentina","Uruguay","Perú"],a:1},

{c:"Ciencia",q:"¿Cuál es el planeta más caliente del sistema solar?",o:["Mercurio","Venus","Marte","Júpiter"],a:1},
{c:"Ciencia",q:"¿Cuántas lunas tiene la Tierra?",o:["1","2","3","Ninguna"],a:0},
{c:"Ciencia",q:"¿Qué galaxia contiene a nuestro sistema solar?",o:["Andrómeda","Vía Láctea","Triángulo","Sombrero"],a:1},
{c:"Ciencia",q:"¿Qué instrumento se usa para observar las estrellas?",o:["Microscopio","Telescopio","Periscopio","Estetoscopio"],a:1},
{c:"Ciencia",q:"¿Qué gas forma la mayor parte de la atmósfera terrestre?",o:["Oxígeno","Nitrógeno","Argón","Dióxido de carbono"],a:1},
{c:"Ciencia",q:"¿Cuál es el símbolo químico del hierro?",o:["Hi","Fe","Ir","He"],a:1},
{c:"Ciencia",q:"¿Cuál es el símbolo químico del sodio?",o:["So","Na","Sd","S"],a:1},
{c:"Ciencia",q:"¿Qué elemento es el más abundante del universo?",o:["Oxígeno","Hidrógeno","Helio","Carbono"],a:1},
{c:"Ciencia",q:"¿Qué órgano produce la insulina?",o:["Hígado","Páncreas","Riñón","Bazo"],a:1},
{c:"Ciencia",q:"¿Cuántas cámaras tiene el corazón humano?",o:["2","3","4","5"],a:2},
{c:"Ciencia",q:"¿Qué parte del ojo controla la entrada de luz?",o:["Retina","Pupila","Córnea","Nervio óptico"],a:1},
{c:"Ciencia",q:"¿Qué célula transporta el oxígeno en la sangre?",o:["Glóbulo blanco","Glóbulo rojo","Plaqueta","Neurona"],a:1},
{c:"Ciencia",q:"¿Cuántos sentidos se reconocen tradicionalmente en el ser humano?",o:["3","4","5","6"],a:2},
{c:"Ciencia",q:"¿Qué animal pone huevos siendo mamífero?",o:["Murciélago","Ornitorrinco","Delfín","Koala"],a:1},
{c:"Ciencia",q:"¿Qué grupo de animales tiene sangre fría?",o:["Aves","Reptiles","Mamíferos","Primates"],a:1},
{c:"Ciencia",q:"¿Cómo se llama el proceso por el que la oruga se vuelve mariposa?",o:["Mitosis","Metamorfosis","Fotosíntesis","Simbiosis"],a:1},
{c:"Ciencia",q:"¿Qué animal es el rey de la selva por tradición?",o:["Tigre","León","Elefante","Gorila"],a:1},
{c:"Ciencia",q:"¿Qué estructura protege el cerebro?",o:["Columna","Cráneo","Costillas","Pelvis"],a:1},
{c:"Ciencia",q:"¿Cuál es el estado del agua a menos de cero grados?",o:["Líquido","Sólido","Gaseoso","Plasma"],a:1},
{c:"Ciencia",q:"¿Qué energía produce un panel solar?",o:["Térmica","Eléctrica","Química","Nuclear"],a:1},
{c:"Ciencia",q:"¿Qué aparato mide la presión atmosférica?",o:["Termómetro","Barómetro","Anemómetro","Higrómetro"],a:1},
{c:"Ciencia",q:"¿Qué científico propuso las leyes del movimiento?",o:["Galileo","Newton","Kepler","Bohr"],a:1},
{c:"Ciencia",q:"¿Quién desarrolló la tabla periódica moderna?",o:["Curie","Mendeléyev","Lavoisier","Dalton"],a:1},
{c:"Ciencia",q:"¿Qué estudia la genética?",o:["Los minerales","La herencia","Los astros","El clima"],a:1},
{c:"Ciencia",q:"¿Qué tipo de roca se forma por el enfriamiento del magma?",o:["Sedimentaria","Ígnea","Metamórfica","Caliza"],a:1},
{c:"Ciencia",q:"¿Qué fenómeno separa la luz en colores?",o:["Reflexión","Refracción","Absorción","Difusión"],a:1},
{c:"Ciencia",q:"¿Cuál es la unidad básica de la vida?",o:["Átomo","Célula","Molécula","Tejido"],a:1},
{c:"Ciencia",q:"¿Qué animal marino tiene el cerebro más grande?",o:["Delfín","Cachalote","Tiburón","Orca"],a:1},
{c:"Ciencia",q:"¿Cuántos grados tiene el ángulo de un triángulo en total?",o:["90","180","270","360"],a:1},
{c:"Ciencia",q:"¿Qué gas usan los globos para flotar?",o:["Oxígeno","Helio","Nitrógeno","Argón"],a:1},
{c:"Ciencia",q:"¿Qué animal tiene el periodo de gestación más largo?",o:["Ballena","Elefante","Rinoceronte","Jirafa"],a:1},
{c:"Ciencia",q:"¿Qué invento permitió ver microorganismos por primera vez?",o:["Telescopio","Microscopio","Prisma","Espejo"],a:1},
{c:"Ciencia",q:"¿Cuál es el hueso más pequeño del cuerpo humano?",o:["Estribo","Falange","Rótula","Costilla"],a:0},

{c:"Historia",q:"¿Qué país construyó el Canal de Panamá inicialmente?",o:["Estados Unidos","Francia","Reino Unido","España"],a:1},
{c:"Historia",q:"¿Quién fue el primer emperador de Roma?",o:["Julio César","Augusto","Nerón","Trajano"],a:1},
{c:"Historia",q:"¿Qué famoso general cruzó los Alpes con elefantes?",o:["Julio César","Aníbal","Alejandro","Escipión"],a:1},
{c:"Historia",q:"¿Quién conquistó el Imperio Persa en el siglo IV a. C.?",o:["Julio César","Alejandro Magno","Darío","Ciro"],a:1},
{c:"Historia",q:"¿Qué civilización inventó la escritura cuneiforme?",o:["Egipcia","Sumeria","Fenicia","Griega"],a:1},
{c:"Historia",q:"¿En qué país nació la democracia antigua?",o:["Roma","Grecia","Egipto","Persia"],a:1},
{c:"Historia",q:"¿Qué peste asoló Europa en el siglo XIV?",o:["Viruela","Peste negra","Cólera","Tifus"],a:1},
{c:"Historia",q:"¿Quién fue el primer presidente de México?",o:["Juárez","Guadalupe Victoria","Iturbide","Madero"],a:1},
{c:"Historia",q:"¿Quién lideró la Revolución Rusa de 1917?",o:["Stalin","Lenin","Trotski","Kerenski"],a:1},
{c:"Historia",q:"¿En qué año se firmó la independencia de Estados Unidos?",o:["1776","1789","1801","1750"],a:0},
{c:"Historia",q:"¿Qué imperio dominó España durante casi ocho siglos en la Edad Media?",o:["Romano","Musulmán","Otomano","Bizantino"],a:1},
{c:"Historia",q:"¿Qué reina financió el viaje de Colón?",o:["Isabel I de Inglaterra","Isabel de Castilla","María Teresa","Juana la Loca"],a:1},
{c:"Historia",q:"¿Qué océano cruzó Colón en 1492?",o:["Pacífico","Atlántico","Índico","Ártico"],a:1},
{c:"Historia",q:"¿Qué invento revolucionó el transporte en el siglo XIX?",o:["El automóvil","La máquina de vapor","El avión","La bicicleta"],a:1},
{c:"Historia",q:"¿Quiénes fueron los primeros en volar un avión motorizado?",o:["Santos Dumont","Hermanos Wright","Lindbergh","Von Braun"],a:1},
{c:"Historia",q:"¿Qué muro rodeaba la antigua ciudad de Constantinopla?",o:["Muro de Adriano","Murallas Teodosianas","Muralla China","Limes"],a:1},
{c:"Historia",q:"¿Qué guerra terminó con el Tratado de Versalles?",o:["Guerra Civil","Primera Guerra Mundial","Segunda Guerra Mundial","Guerra Fría"],a:1},
{c:"Historia",q:"¿Qué país fue el primero en dar el voto a las mujeres a nivel nacional?",o:["Estados Unidos","Nueva Zelanda","Reino Unido","Francia"],a:1},
{c:"Historia",q:"¿Qué faraona gobernó Egipto como rey?",o:["Nefertiti","Hatshepsut","Cleopatra","Nefertari"],a:1},
{c:"Historia",q:"¿Qué imperio construyó la ciudad de Cusco?",o:["Maya","Azteca","Inca","Chavín"],a:2},
{c:"Historia",q:"¿En qué siglo se inventó la imprenta de tipos móviles en Europa?",o:["XIII","XV","XVII","XIX"],a:1},
{c:"Historia",q:"¿Qué explorador llegó primero al Polo Sur?",o:["Scott","Amundsen","Shackleton","Nansen"],a:1},
{c:"Historia",q:"¿Qué ciudad fue la capital del Imperio Bizantino?",o:["Roma","Constantinopla","Atenas","Alejandría"],a:1},
{c:"Historia",q:"¿Qué revolución comenzó con la toma de la Bastilla?",o:["Rusa","Francesa","Industrial","Americana"],a:1},
{c:"Historia",q:"¿Qué país lanzó las primeras bombas atómicas usadas en guerra?",o:["Alemania","Estados Unidos","Unión Soviética","Reino Unido"],a:1},
{c:"Historia",q:"¿Qué antigua maravilla estaba en Alejandría?",o:["Coloso","Faro","Jardines","Mausoleo"],a:1},
{c:"Historia",q:"¿Quién escribió La Odisea?",o:["Virgilio","Homero","Sófocles","Platón"],a:1},
{c:"Historia",q:"¿Qué filósofo griego fue maestro de Alejandro Magno?",o:["Sócrates","Aristóteles","Platón","Epicuro"],a:1},
{c:"Historia",q:"¿Qué imperio precolombino habitó la península de Yucatán?",o:["Inca","Maya","Azteca","Zapoteca"],a:1},
{c:"Historia",q:"¿En qué año se fundó la Cruz Roja?",o:["1863","1901","1918","1945"],a:0},
{c:"Historia",q:"¿Qué presidente estadounidense fue asesinado en Dallas en 1963?",o:["Roosevelt","Kennedy","Nixon","Truman"],a:1},
{c:"Historia",q:"¿Qué nave llevó a los primeros humanos a la Luna?",o:["Apolo 11","Sputnik","Vostok","Challenger"],a:0},
{c:"Historia",q:"¿Qué civilización desarrolló los primeros calendarios de 365 días?",o:["Griega","Egipcia","Romana","China"],a:1},

{c:"Entretenimiento",q:"¿Qué película animada tiene un león llamado Simba?",o:["Madagascar","El Rey León","Zootopia","Kung Fu Panda"],a:1},
{c:"Entretenimiento",q:"¿Cómo se llama la princesa de La Sirenita?",o:["Aurora","Ariel","Jasmine","Bella"],a:1},
{c:"Entretenimiento",q:"¿Qué estudio creó Toy Story?",o:["DreamWorks","Pixar","Illumination","Blue Sky"],a:1},
{c:"Entretenimiento",q:"¿Qué personaje amarillo vive en una piña bajo el mar?",o:["Patricio","Bob Esponja","Calamardo","Don Cangrejo"],a:1},
{c:"Entretenimiento",q:"¿Qué serie tiene dragones y la casa Stark?",o:["Vikingos","Juego de Tronos","The Witcher","Merlín"],a:1},
{c:"Entretenimiento",q:"¿Qué instrumento toca un baterista?",o:["Guitarra","Batería","Piano","Violín"],a:1},
{c:"Entretenimiento",q:"¿Cuántas notas musicales básicas existen?",o:["5","6","7","8"],a:2},
{c:"Entretenimiento",q:"¿Qué género musical nació en Jamaica?",o:["Salsa","Reggae","Cumbia","Bachata"],a:1},
{c:"Entretenimiento",q:"¿De qué país es originaria la bachata?",o:["Cuba","República Dominicana","Puerto Rico","Colombia"],a:1},
{c:"Entretenimiento",q:"¿De qué país es originaria la cumbia?",o:["Colombia","México","Perú","Argentina"],a:0},
{c:"Entretenimiento",q:"¿Qué cantante británico es conocido por Shape of You?",o:["Sam Smith","Ed Sheeran","Harry Styles","Elton John"],a:1},
{c:"Entretenimiento",q:"¿Qué banda británica cantó Bohemian Rhapsody?",o:["The Beatles","Queen","Pink Floyd","The Who"],a:1},
{c:"Entretenimiento",q:"¿Qué cantante colombiano es conocido como el Caballero de la Salsa?",o:["Carlos Vives","Jorge Celedón","Gilberto Santa Rosa","Juan Luis Guerra"],a:2},
{c:"Entretenimiento",q:"¿Qué instrumento se asocia con Escocia?",o:["Arpa","Gaita","Acordeón","Banjo"],a:1},
{c:"Entretenimiento",q:"¿Qué juego usa fichas con puntos del 0 al 6?",o:["Ajedrez","Dominó","Damas","Parchís"],a:1},
{c:"Entretenimiento",q:"¿Cuántas cartas tiene una baraja francesa sin comodines?",o:["48","52","54","56"],a:1},
{c:"Entretenimiento",q:"¿Qué videojuego popularizó la construcción de bloques?",o:["Fortnite","Minecraft","Terraria","Roblox"],a:1},
{c:"Entretenimiento",q:"¿Qué compañía creó la consola PlayStation?",o:["Nintendo","Sony","Microsoft","Sega"],a:1},
{c:"Entretenimiento",q:"¿Qué compañía creó la consola Xbox?",o:["Sony","Microsoft","Nintendo","Atari"],a:1},
{c:"Entretenimiento",q:"¿Qué plataforma de videos fue comprada por Google en 2006?",o:["Vimeo","YouTube","Dailymotion","Twitch"],a:1},
{c:"Entretenimiento",q:"¿Qué red social se caracteriza por fotos y stories?",o:["LinkedIn","Instagram","Reddit","X"],a:1},
{c:"Entretenimiento",q:"¿Qué famoso mago escribió su historia en Hogwarts?",o:["Gandalf","Harry Potter","Merlín","Dumbledore"],a:1},
{c:"Entretenimiento",q:"¿Quién escribió Cien años de soledad?",o:["Vargas Llosa","García Márquez","Borges","Cortázar"],a:1},
{c:"Entretenimiento",q:"¿Quién escribió El Principito?",o:["Saint-Exupéry","Verne","Dumas","Hugo"],a:0},
{c:"Entretenimiento",q:"¿Qué autor creó a Sherlock Holmes?",o:["Agatha Christie","Conan Doyle","Poe","Dickens"],a:1},
{c:"Entretenimiento",q:"¿Qué película muestra dinosaurios en un parque?",o:["Godzilla","Jurassic Park","King Kong","Ice Age"],a:1},
{c:"Entretenimiento",q:"¿Cómo se llama el archienemigo de Superman?",o:["Joker","Lex Luthor","Thanos","Loki"],a:1},
{c:"Entretenimiento",q:"¿Qué superhéroe lleva un escudo con una estrella?",o:["Iron Man","Capitán América","Thor","Hulk"],a:1},
{c:"Entretenimiento",q:"¿Qué color de kryptonita debilita a Superman?",o:["Roja","Verde","Azul","Negra"],a:1},
{c:"Entretenimiento",q:"¿Qué festival de cine entrega la Palma de Oro?",o:["Venecia","Cannes","Berlín","Sundance"],a:1},
{c:"Entretenimiento",q:"¿En qué país se celebra el Festival de Eurovisión cada año?",o:["Siempre en Francia","Cambia cada año","Siempre en Suecia","Siempre en Reino Unido"],a:1},
{c:"Entretenimiento",q:"¿Qué baile popularizó la película Grease?",o:["Rock and roll","Tango","Vals","Salsa"],a:0},
{c:"Entretenimiento",q:"¿Qué instrumento tiene pedales y cuerdas y se toca sentado?",o:["Violín","Arpa","Flauta","Trompeta"],a:1},
{c:"Entretenimiento",q:"¿Qué película trata sobre un niño abandonado en casa en Navidad?",o:["Elf","Mi pobre angelito","Polar Express","Grinch"],a:1},

{c:"Deportes",q:"¿Cuántos jugadores tiene un equipo de béisbol en el campo?",o:["8","9","10","11"],a:1},
{c:"Deportes",q:"¿Cuántos tiempos tiene un partido de básquetbol de la NBA?",o:["2","3","4","5"],a:2},
{c:"Deportes",q:"¿Cuánto dura cada tiempo en la NBA?",o:["10 min","12 min","15 min","20 min"],a:1},
{c:"Deportes",q:"¿Qué país ganó el Mundial de fútbol de 2018?",o:["Croacia","Francia","Alemania","Brasil"],a:1},
{c:"Deportes",q:"¿Qué país ganó el Mundial de fútbol de 2014?",o:["Argentina","Alemania","Brasil","España"],a:1},
{c:"Deportes",q:"¿Qué país ganó el Mundial de fútbol de 2010?",o:["Países Bajos","España","Alemania","Uruguay"],a:1},
{c:"Deportes",q:"¿En qué país se jugó el Mundial de 2014?",o:["Sudáfrica","Brasil","Rusia","Catar"],a:1},
{c:"Deportes",q:"¿Cuántos jugadores forman un equipo de rugby en cancha?",o:["11","13","15","17"],a:2},
{c:"Deportes",q:"¿En qué deporte se usa una pelota ovalada y se marca un try?",o:["Fútbol americano","Rugby","Béisbol","Hockey"],a:1},
{c:"Deportes",q:"¿Cuántos anillos olímpicos representan continentes?",o:["4","5","6","7"],a:1},
{c:"Deportes",q:"¿Dónde se celebraron los Juegos Olímpicos de 2016?",o:["Londres","Río de Janeiro","Tokio","Pekín"],a:1},
{c:"Deportes",q:"¿Dónde se celebraron los Juegos Olímpicos de 2012?",o:["Pekín","Londres","Atenas","Sídney"],a:1},
{c:"Deportes",q:"¿Qué deporte practica Rafael Nadal?",o:["Golf","Tenis","Pádel","Baloncesto"],a:1},
{c:"Deportes",q:"¿En qué superficie es más famoso Rafael Nadal?",o:["Césped","Arcilla","Cemento","Sintética"],a:1},
{c:"Deportes",q:"¿Cuántos jugadores hay en un partido de tenis individual?",o:["1","2","3","4"],a:1},
{c:"Deportes",q:"¿Cómo se llama el punto cuando hay empate a 40 en tenis?",o:["Set","Deuce o iguales","Break","Ace"],a:1},
{c:"Deportes",q:"¿Qué significa un ace en tenis?",o:["Falta doble","Saque sin devolución","Punto perdido","Cambio de lado"],a:1},
{c:"Deportes",q:"¿Cuántos minutos dura un tiempo en fútbol reglamentario?",o:["30","40","45","50"],a:2},
{c:"Deportes",q:"¿Cuántas tarjetas amarillas equivalen a una expulsión?",o:["1","2","3","4"],a:1},
{c:"Deportes",q:"¿Desde qué distancia se lanza un penalti en fútbol?",o:["9 metros","11 metros","13 metros","15 metros"],a:1},
{c:"Deportes",q:"¿Qué liga de fútbol es la principal de Inglaterra?",o:["La Liga","Premier League","Serie A","Bundesliga"],a:1},
{c:"Deportes",q:"¿Qué liga de fútbol es la principal de Alemania?",o:["Ligue 1","Bundesliga","Eredivisie","Serie A"],a:1},
{c:"Deportes",q:"¿De qué país es el club Boca Juniors?",o:["Uruguay","Argentina","Chile","Brasil"],a:1},
{c:"Deportes",q:"¿En qué deporte destacó Muhammad Ali?",o:["Lucha","Boxeo","Kárate","Judo"],a:1},
{c:"Deportes",q:"¿Cuántos jugadores tiene un equipo de waterpolo en el agua?",o:["5","6","7","8"],a:2},
{c:"Deportes",q:"¿Qué se usa para golpear la pelota en hockey sobre hielo?",o:["Raqueta","Stick","Bate","Palo de golf"],a:1},
{c:"Deportes",q:"¿Cómo se llama el disco usado en hockey sobre hielo?",o:["Puck","Bola","Volante","Pelota"],a:0},
{c:"Deportes",q:"¿En qué deporte se compite por el maillot amarillo?",o:["Atletismo","Ciclismo","Natación","Motociclismo"],a:1},
{c:"Deportes",q:"¿Qué distancia tiene una piscina olímpica?",o:["25 metros","50 metros","75 metros","100 metros"],a:1},
{c:"Deportes",q:"¿Cuántas vueltas tiene una carrera de 400 metros en pista?",o:["Media vuelta","Una vuelta","Dos vueltas","Cuatro vueltas"],a:1},
{c:"Deportes",q:"¿Qué deporte olímpico combina cinco disciplinas?",o:["Decatlón","Pentatlón moderno","Triatlón","Biatlón"],a:1},
{c:"Deportes",q:"¿Cuántas pruebas tiene el decatlón?",o:["7","8","10","12"],a:2},
{c:"Deportes",q:"¿Qué país tiene el estadio Maracaná?",o:["Argentina","Brasil","Uruguay","Colombia"],a:1},

{c:"Sorpresa",q:"¿Qué animal no puede sacar la lengua?",o:["Cocodrilo","Perro","Gato","Camaleón"],a:0},
{c:"Sorpresa",q:"¿Cuánto tiempo puede vivir un caracol durmiendo?",o:["Un día","Hasta tres años","Un mes","Una semana"],a:1},
{c:"Sorpresa",q:"¿Qué fruta tiene sus semillas por fuera?",o:["Manzana","Fresa","Uva","Pera"],a:1},
{c:"Sorpresa",q:"¿Qué animal tiene la piel azul debajo del pelaje?",o:["Oso polar","Tigre","Lobo","Zorro"],a:0},
{c:"Sorpresa",q:"¿Qué país tiene más ovejas que personas?",o:["Australia","Nueva Zelanda","Escocia","Irlanda"],a:1},
{c:"Sorpresa",q:"¿Cuántos huesos tiene el cuello de una jirafa?",o:["7","12","24","32"],a:0},
{c:"Sorpresa",q:"¿Qué animal duerme hasta 20 horas al día?",o:["Perezoso","Koala","León","Gato"],a:1},
{c:"Sorpresa",q:"¿Qué insecto puede cargar 50 veces su peso?",o:["Mosca","Hormiga","Mariposa","Libélula"],a:1},
{c:"Sorpresa",q:"¿Qué órgano puede regenerarse casi por completo?",o:["Corazón","Hígado","Pulmón","Riñón"],a:1},
{c:"Sorpresa",q:"¿Cuántas veces late el corazón humano al día aproximadamente?",o:["10 mil","50 mil","100 mil","500 mil"],a:2},
{c:"Sorpresa",q:"¿Qué país celebra el Año Nuevo primero por su huso horario?",o:["Japón","Kiribati","Australia","Nueva Zelanda"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene la bandera más antigua aún en uso?",o:["Reino Unido","Dinamarca","Francia","Japón"],a:1},
{c:"Sorpresa",q:"¿Qué país no tiene ríos naturales permanentes?",o:["Egipto","Arabia Saudita","Chile","Portugal"],a:1},
{c:"Sorpresa",q:"¿Cuál es el edificio más alto del mundo?",o:["Torre Eiffel","Burj Khalifa","Empire State","Shanghai Tower"],a:1},
{c:"Sorpresa",q:"¿En qué país está el Burj Khalifa?",o:["Catar","Emiratos Árabes Unidos","Arabia Saudita","Kuwait"],a:1},
{c:"Sorpresa",q:"¿Qué idioma tiene más caracteres en su escritura?",o:["Japonés","Chino","Coreano","Árabe"],a:1},
{c:"Sorpresa",q:"¿Cuánto pesa aproximadamente una nube típica?",o:["Nada","Cientos de toneladas","Un kilo","Diez kilos"],a:1},
{c:"Sorpresa",q:"¿Qué color de sangre tiene un pulpo?",o:["Roja","Azul","Verde","Amarilla"],a:1},
{c:"Sorpresa",q:"¿Qué planeta podría flotar en el agua por su densidad?",o:["Marte","Saturno","Venus","Mercurio"],a:1},
{c:"Sorpresa",q:"¿Cuántos años luz nos separan de la estrella más cercana tras el Sol?",o:["Menos de 1","Unos 4","Unos 20","Unos 100"],a:1},
{c:"Sorpresa",q:"¿Qué alimento fue llevado al espacio por primera vez?",o:["Pizza","Puré en tubo","Chocolate","Manzana"],a:1},
{c:"Sorpresa",q:"¿Qué animal fue el primero en ser clonado con éxito?",o:["Un perro","Una oveja","Un ratón","Una vaca"],a:1},
{c:"Sorpresa",q:"¿Cómo se llamaba la oveja clonada en 1996?",o:["Molly","Dolly","Polly","Sally"],a:1},
{c:"Sorpresa",q:"¿Qué inventó accidentalmente un científico buscando un pegamento fuerte?",o:["Velcro","Notas adhesivas","Cinta aislante","Grapadora"],a:1},
{c:"Sorpresa",q:"¿Qué invento surgió al derretirse un chocolate cerca de un radar?",o:["Nevera","Microondas","Tostadora","Licuadora"],a:1},
{c:"Sorpresa",q:"¿Qué bebida gaseosa se creó originalmente como jarabe medicinal?",o:["Fanta","Coca-Cola","Sprite","Pepsi"],a:1},
{c:"Sorpresa",q:"¿Cuántos idiomas oficiales tiene Sudáfrica?",o:["2","4","6","11 o más"],a:3},
{c:"Sorpresa",q:"¿Qué país cambió de nombre a Esuatini en 2018?",o:["Lesoto","Suazilandia","Namibia","Botsuana"],a:1},
{c:"Sorpresa",q:"¿Qué animal puede sobrevivir en el espacio exterior?",o:["Cucaracha","Tardígrado","Hormiga","Escorpión"],a:1},
{c:"Sorpresa",q:"¿Qué parte del cuerpo tiene su propio ecosistema de bacterias?",o:["Solo la boca","El intestino","Solo la piel","Solo el pelo"],a:1},
{c:"Sorpresa",q:"¿Cuál es el sonido más rápido que puede hacer un animal?",o:["Aleteo del colibrí","Chasquido del camarón pistola","Rugido del león","Canto del grillo"],a:1},
{c:"Sorpresa",q:"¿Qué material se recicla infinitas veces sin perder calidad?",o:["Plástico","Vidrio","Papel","Cartón"],a:1},
{c:"Sorpresa",q:"¿Qué país tiene un desierto y glaciares a la vez?",o:["Egipto","Chile","Marruecos","Libia"],a:1}
];

const RETOS = [
 "Saluda en 3 idiomas distintos",
 "Imita a un guía turístico presentando esta sala",
 "Di 5 capitales del mundo en 10 segundos",
 "Habla con el acento que elija el grupo hasta tu próximo turno",
 "Imita a un comentarista deportivo narrando este momento",
 "Nombra 5 comidas típicas de distintos países en 15 segundos",
 "Canta 10 segundos de una canción en otro idioma",
 "Di un trabalenguas sin equivocarte",
 "Baila un ritmo de otro país por 10 segundos",
 "Cuenta hasta 10 en otro idioma",
 "¡Haz 10 sentadillas mientras cantas el himno de tu país!",
 "Imita a un animal hasta que alguien adivine cuál es",
 "Di 5 países que empiecen con la letra que elija el grupo",
 "Cuenta un chiste; si nadie se ríe, no ganas los puntos",
 "Habla como robot hasta tu próximo turno",
 "Nombra 5 marcas famosas en 10 segundos",
 "Imita a alguien del grupo hasta que adivinen quién es",
 "Aguanta la risa 15 segundos mientras el grupo intenta hacerte reír",
 "Di el abecedario al revés desde la letra J",
 "Canta el cumpleaños feliz en versión ópera",
 "Inventa una historia de 30 segundos que incluya la palabra pepino",
 "Nombra 5 películas en 10 segundos sin repetir",
 "Haz tu mejor imitación de un presentador de noticias",
 "Describe tu día de ayer usando solo mímica",
 "Di 5 animales que vivan en África en 10 segundos",
 "Habla susurrando hasta tu próximo turno",
 "Haz 15 saltos contando en voz alta",
 "Imita el sonido de 3 instrumentos musicales",
 "Nombra 5 ríos o mares del mundo en 15 segundos",
 "Haz una pose de estatua durante 20 segundos sin moverte",
 "Vende un objeto que tengas cerca como si fuera un tesoro",
 "Di 5 palabras que rimen con la palabra que elija el grupo",
 "Canta cualquier canción cambiando la letra por 'la la la'",
 "Imita a un turista perdido preguntando direcciones",
 "Nombra 5 profesiones en 10 segundos",
 "Haz el saludo típico de 3 culturas diferentes",
 "Cuenta una anécdota tuya en menos de 20 segundos",
 "Di 5 postres del mundo en 15 segundos",
 "Imita el acento de otro país de habla hispana",
 "Aplaude un ritmo y que el grupo lo repita"
];
